In [1]:
import pandas as pd
import pandasql as ps

In [2]:
titanic = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [3]:
titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
ps.sqldf("""SELECT 
    *
    FROM titanic
""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,None,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,None,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,None,Q

If we want to see only top 5 points from our dataset and instead of using complete name we can import from a shorter name

In [5]:
ps.sqldf("""
SELECT df.* FROM titanic as df LIMIT 5
""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

SELECTING ONLY SPECIFIC COLUMNS

In [6]:
ps.sqldf("""
SELECT df.PassengerId ,df.Survived FROM titanic AS df LIMIT 5 """)

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0

We can rename long columns as shorter columns

In [7]:
ps.sqldf("""
SELECT df.PassengerId AS id_of_passenger,df.Survived AS is_survived FROM titanic AS df LIMIT 10""")

   id_of_passenger  is_survived
0                1            0
1                2            1
2                3            1
3                4            1
4                5            0
5                6            0
6                7            0
7                8            0
8                9            1
9               10            1

WHERE

If you want only specific rows based on a condition, you can mention these conditions in "WHERE" clause.
"WHERE" works row by row e.g. if the condition is Age = 10, in each row the query will check if Age is equal to 10 and if yes, then it will take that row, otherwise not.

In [8]:
ps.sqldf("""
SELECT df.* FROM titanic AS df
WHERE df.age=5""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,None,S
1,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.0,4,2,347077,31.3875,None,S
2,449,1,3,"Baclini, Miss. Marie Catherine",female,5.0,2,1,2666,19.2583,None,C
3,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.4750,None,S

NULL

 To find mising values in the data, we can use "NULL" keyword. Just be mindful that NULL works with "IS" and not with "=". For example, "Age IS NULL" is the correct way of finding nulls in Age column and "Age = NULL" is not (and will throw error)

In [9]:
ps.sqldf("""
SELECT df.* FROM titanic AS df
WHERE df.age IS NULL""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,6,0,3,"Moran, Mr. James",male,None,0,0,330877,8.4583,None,Q
1,18,1,2,"Williams, Mr. Charles Eugene",male,None,0,0,244373,13.0000,None,S
2,20,1,3,"Masselmani, Mrs. Fatima",female,None,0,0,2649,7.2250,None,C
3,27,0,3,"Emir, Mr. Farred Chehab",male,None,0,0,2631,7.2250,None,C
4,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,None,0,0,330959,7.8792,None,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
172,860,0,3,"Razi, Mr. Raihed",male,None,0,0,2629,7.2292,None,C
173,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,None,8,2,CA. 2343,69.5500,None,S
174,869,0,3,"van Melkebeke, Mr. Philemon",male,None,0,0,345777,9.5000,None,S
175,879,0,3,"Laleff, Mr. Kristo",male,None,0,0,349217,7.8958,None,S
176,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,None,S

YOU CAN GET NON NULL ROWS BY USING "IS NOT NULL"

In [10]:
ps.sqldf("""
SELECT df.* from titanic AS df 
WHERE df.age IS NOT NULL""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...,...
709,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,None,Q
710,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,None,S
711,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
712,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
713,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,None,Q

Use "BETWEEN" to filter between two numerical values

In [11]:
ps.sqldf("""
SELECT df.* FROM titanic AS df
WHERE df.age BETWEEN 5 AND 10""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,None,S
1,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,None,S
2,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,None,S
3,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,None,S
4,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,None,S
5,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.0,4,2,347077,31.3875,None,S
6,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.0,4,2,347077,31.3875,None,S
7,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.0,0,2,C.A. 31921,26.2500,None,S
8,279,0,3,"Rice, Master. Eric",male,7.0,4,1,382652,29.1250,None,Q
9,420,0,3,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,None,S
10,449,1,3,"Baclini, Miss. Marie Catherine",female,5.0,2,1,2666,19.2583,None,C
11,481,0,3,"Goodwin, Master. Harold Victor",male,9.0,5,2,CA 2144,46.9000,None,S
12,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.0,1,1,C.A. 37671,15.9000,None,S
13,536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.2500,None,S
14,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.0,4,2,347082,31.2750,None,S
15,550,1,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,None,S
16,635,0,3,"Skoog, Miss. Mabel",female,9.0,3,2,347088,27.9000,None,S
17,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,None,S
18,752,1,3,"Moor, Master. Meier",male,6.0,0,1,392096,12.4750,E121,S
19,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.4750,None,S
20,788,0,3,"Rice, Master. George Hugh",male,8.0,4,1,382652,29.1250,None,Q
21,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,None,S
22,820,0,3,"Skoog, Master. Karl Thorsten",male,10.0,3,2,347088,27.9000,None,S
23,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,None,C

You can specify multiple conditions using "AND" or "OR" operators. Here are some examples

In [12]:
ps.sqldf("""
SELECT df.* from titanic AS df
WHERE (df.age<1 AND df.sex="female") OR (df.age>60 AND df.sex="female")
""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S
1,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,None,C
2,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.00,0,0,4134,9.5875,None,S
3,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,None,C
4,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.00,0,0,113572,80.0000,B28,None

Using "AND" and "OR" together might be tricky at times. It is best to use parantheses to enforce which conditions will be evaluated together. E.g. in the above example we have four conditions in total. First the two conditions inside the parantheses will be evaluated separately using "AND". And then the output of those two will be evaluated using "OR" statement

If there are multiple values you want to filter in a column, you can use "IN" keyword

In [13]:
ps.sqldf("""
SELECT df.* FROM titanic AS df
WHERE df.Embarked IN ('S','C')""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...,...
807,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,None,S
808,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,None,S
809,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
810,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,None,S
811,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [14]:
ps.sqldf("""
SELECT df.* FROM titanic AS df
WHERE df.age IN (25,34,43)""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
1,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
2,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,None,S
3,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,None,S
4,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0000,None,S
5,203,0,3,"Johanson, Mr. Jakob Alfred",male,34.0,0,0,3101264,6.4958,None,S
6,247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25.0,0,0,347071,7.7750,None,S
7,268,1,3,"Persson, Mr. Ernst Ulrik",male,25.0,1,0,347083,7.7750,None,S
8,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,None,S
9,315,0,2,"Hart, Mr. Benjamin",male,43.0,1,1,F.C.C. 13529,26.2500,None,S
10,344,0,2,"Sedgwick, Mr. Charles Frederick Waddington",male,25.0,0,0,244361,13.0000,None,S
11,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,None,S
12,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
13,406,0,2,"Gale, Mr. Shadrach",male,34.0,1,0,28664,21.0000,None,S
14,417,1,2,"Drew, Mrs. James Vivian (Lulu Thorne Christian)",female,34.0,1,1,28220,32.5000,None,S
15,443,0,3,"Petterson, Mr. Johan Emil",male,25.0,1,0,347076,7.7750,None,S
16,448,1,1,"Seward, Mr. Frederic Kimber",male,34.0,0,0,113794,26.5500,None,S
17,462,0,3,"Morley, Mr. William",male,34.0,0,0,364506,8.0500,None,S
18,477,0,2,"Renouf, Mr. Peter Henry",male,34.0,1,0,31027,21.0000,None,S
19,485,1,1,"Bishop, Mr. Dickinson H",male,25.0,1,0,11967,91.0792,B49,C
20,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S
21,517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.0,0,0,C.A. 34260,10.5000,F33,S
22,577,1,2,"Garside, Miss. Ethel",female,34.0,0,0,243880,13.0000,None,S
23,581,1,2,"Christy, Miss. Julie Rachel",female,25.0,1,1,237789,30.0000,None,S
24,617,0,3,"Danbom, Mr. Ernst Gilbert",male,34.0,1,1,347080,14.4000,None,S
25,667,0,2,"Butler, Mr. Reginald Fenton",male,25.0,0,0,234686,13.0000,None,S
26,669,0,3,"Cook, Mr. Jacob",male,43.0,0,0,A/5 3536,8.0500,None,S
27,679,0,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,1,6,CA 2144,46.9000,None,S
28,686,0,2,"Laroche, Mr. Joseph Philippe Lemercier",male,25.0,1,2,SC/Paris 2123,41.5792,None,C
29,694,0,3,"Saad, Mr. Khalil",male,25.0,0,0,2672,7.2250,None,C
30,704,0,3,"Gallagher, Mr. Martin",male,25.0,0,0,36864,7.7417,None,Q
31,723,0,2,"Gillespie, Mr. William Henry",male,34.0,0,0,12233,13.0000,None,S
32,729,0,2,"Bryhl, Mr. Kurt Arnold Gottfrid",male,25.0,1,0,236853,26.0000,None,S
33,730,0,3,"Ilmakangas, Miss. Pieta Sofia",female,25.0,1,0,STON/O2. 3101271,7.9250,None,S
34,759,0,3,"Theobald, Mr. Thomas Leonard",male,34.0,0,0,363294,8.0500,None,S
35,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S
36,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,None,S
37,786,0,3,"Harmer, Mr. Abraham (David Lishin)",male,25.0,0,0,374887,7.2500,None,S
38,795,0,3,"Dantcheff, Mr. Ristiu",male,25.0,0,0,349203,7.8958,None,S
39,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,None,S
40,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.0,0,0,C 7075,6.4500,None,S
41,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,None,S
42,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,None,S

For text/string columns, a powerful way of filtering is using "LIKE" keyword. It works by the specifying the substring you want in a string and surrounding the substring with '%'s. Here is how it looks with examples below -
<ul>
    <li>For Names starting with "ABC" - Name LIKE "ABC%"</li>
    <li>For Names ending with "ABC" - Name LIKE "%ABC"</li>
    <li>For Names which contain "ABC" - Name LIKE "%ABC%"</li>
</ul>

In [15]:
ps.sqldf("""
SELECT df.* FROM titanic AS df
WHERE df.name LIKE "%Mr.%"
LIMIT 5
""")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
2,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,None,Q
3,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
4,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,None,S

As you can see the "LIKE" condition is not case sensitive i.e. both 'mr.' and 'MR.' will be found with the same search string

You can create new columns out of existing columns. Here are some examples-

In [16]:
ps.sqldf("""
SELECT df.age,
df.age*df.age  AS age_squared
FROM titanic AS df
LIMIT 7

""")

    Age  age_squared
0  22.0        484.0
1  38.0       1444.0
2  26.0        676.0
3  35.0       1225.0
4  35.0       1225.0
5   NaN          NaN
6  54.0       2916.0

CONCATENATING TWO STRINGS AS ONE

In [17]:
ps.sqldf("""
SELECT
df.Sex , df.Ticket ,
df.Sex || df.Ticket AS sex_plus_ticker
FROM titanic AS df
LIMIT 10""")

      Sex            Ticket         sex_plus_ticker
0    male         A/5 21171           maleA/5 21171
1  female          PC 17599          femalePC 17599
2  female  STON/O2. 3101282  femaleSTON/O2. 3101282
3  female            113803            female113803
4    male            373450              male373450
5    male            330877              male330877
6    male             17463               male17463
7    male            349909              male349909
8  female            347742            female347742
9  female            237736            female237736

CASE WHEN

You can use CASE WHEN to create new columns based on the specified conditions. Here is an example of the same -

In [18]:
#Using CASE WHEN to create buckets for age
ps.sqldf("""

SELECT 
    df.Name,
    df.PassengerID,
    df.Age,
    CASE WHEN df.Age IS NULL THEN '0. Missing'
        WHEN df.Age <18 THEN '1. 1-17'
        WHEN df.Age <60 THEN '2. 18-60'
    ELSE '3. 60+' END AS age_bucket
FROM titanic AS df
LIMIT 50   
    
""")

,Name,PassengerId,Age,age_bucket
0,"Braund, Mr. Owen Harris",1,22.0,2. 18-60
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,38.0,2. 18-60
2,"Heikkinen, Miss. Laina",3,26.0,2. 18-60
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,35.0,2. 18-60
4,"Allen, Mr. William Henry",5,35.0,2. 18-60
5,"Moran, Mr. James",6,NaN,0. Missing
6,"McCarthy, Mr. Timothy J",7,54.0,2. 18-60
7,"Palsson, Master. Gosta Leonard",8,2.0,1. 1-17
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,27.0,2. 18-60
9,"Nasser, Mrs. Nicholas (Adele Achem)",10,14.0,1. 1-17
10,"Sandstrom, Miss. Marguerite Rut",11,4.0,1. 1-17
11,"Bonnell, Miss. Elizabeth",12,58.0,2. 18-60
12,"Saundercock, Mr. William Henry",13,20.0,2. 18-60
13,"Andersson, Mr. Anders Johan",14,39.0,2. 18-60
14,"Vestrom, Miss. Hulda Amanda Adolfina",15,14.0,1. 1-17
15,"Hewlett, Mrs. (Mary D Kingcome)",16,55.0,2. 18-60
16,"Rice, Master. Eugene",17,2.0,1. 1-17
17,"Williams, Mr. Charles Eugene",18,NaN,0. Missing
18,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",19,31.0,2. 18-60
19,"Masselmani, Mrs. Fatima",20,NaN,0. Missing
20,"Fynney, Mr. Joseph J",21,35.0,2. 18-60
21,"Beesley, Mr. Lawrence",22,34.0,2. 18-60
22,"McGowan, Miss. Anna ""Annie""",23,15.0,1. 1-17
23,"Sloper, Mr. William Thompson",24,28.0,2. 18-60
24,"Palsson, Miss. Torborg Danira",25,8.0,1. 1-17
25,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",26,38.0,2. 18-60
26,"Emir, Mr. Farred Chehab",27,NaN,0. Missing
27,"Fortune, Mr. Charles Alexander",28,19.0,2. 18-60
28,"O'Dwyer, Miss. Ellen ""Nellie""",29,NaN,0. Missing
29,"Todoroff, Mr. Lalio",30,NaN,0. Missing
30,"Uruchurtu, Don. Manuel E",31,40.0,2. 18-60
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",32,NaN,0. Missing
32,"Glynn, Miss. Mary Agatha",33,NaN,0. Missing
33,"Wheadon, Mr. Edward H",34,66.0,3. 60+
34,"Meyer, Mr. Edgar Joseph",35,28.0,2. 18-60
35,"Holverson, Mr. Alexander Oskar",36,42.0,2. 18-60
36,"Mamee, Mr. Hanna",37,NaN,0. Missing
37,"Cann, Mr. Ernest Charles",38,21.0,2. 18-60
38,"Vander Planke, Miss. Augusta Maria",39,18.0,2. 18-60
39,"Nicola-Yarred, Miss. Jamila",40,14.0,1. 1-17
40,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",41,40.0,2. 18-60
41,"Turpin, Mrs. William John Robert (Dorothy Ann ...",42,27.0,2. 18-60
42,"Kraeff, Mr. Theodor",43,NaN,0. Missing
43,"Laroche, Miss. Simonne Marie Anne Andree",44,3.0,1. 1-17
44,"Devaney, Miss. Margaret Delia",45,19.0,2. 18-60
45,"Rogers, Mr. William John",46,NaN,0. Missing
46,"Lennon, Mr. Denis",47,NaN,0. Missing
47,"O'Driscoll, Miss. Bridget",48,NaN,0. Missing
48,"Samaan, Mr. Youssef",49,NaN,0. Missing
49,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",50,18.0,2. 18-60

SUBSTR : function can be used to take out one part from a string upto a certain point in a string column , SUBSTR() function requires three paras (column_name,starting point,number of characters)

In [19]:
ps.sqldf("""
SELECT df.Name,
SUBSTR(df.NAME,2,4) AS SUB_OUTPUT
FROM titanic AS df
LIMIT 5
""")

                                                Name SUB_OUTPUT
0                            Braund, Mr. Owen Harris       raun
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       umin
2                             Heikkinen, Miss. Laina       eikk
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       utre
4                           Allen, Mr. William Henry       llen

<b>LOWER() and UPPER()</b> can be used to convert text columns to lower and upper case, respectively. Here is an example -

In [20]:
ps.sqldf("""
SELECT df.Name,
LOWER(df.Name) AS lower_case,
UPPER(df.Name) AS upper_case
FROM titanic AS df
LIMIT 5
""")

,Name,lower_case,upper_case
0,"Braund, Mr. Owen Harris","braund, mr. owen harris","BRAUND, MR. OWEN HARRIS"
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...","cumings, mrs. john bradley (florence briggs th...","CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH..."
2,"Heikkinen, Miss. Laina","heikkinen, miss. laina","HEIKKINEN, MISS. LAINA"
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)","futrelle, mrs. jacques heath (lily may peel)","FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)"
4,"Allen, Mr. William Henry","allen, mr. william henry","ALLEN, MR. WILLIAM HENRY"

You can get all the unique values in a column using "DISTINCT" keyword

In [21]:
#selecting all distinct value of 'EMBARKED'
ps.sqldf("""
SELECT
DISTINCT df.Embarked
FROM titanic as df
""")

  Embarked
0        S
1        C
2        Q
3     None

In [22]:
#selecting all distinct cabin of 'EMBARKED'
ps.sqldf("""
SELECT
DISTINCT df.Cabin
FROM titanic as df
""")

    Cabin
0    None
1     C85
2    C123
3     E46
4      G6
..    ...
143   E17
144   A24
145   C50
146   B42
147  C148

[148 rows x 1 columns]

# AGGREGATE

In [23]:
ps.sqldf("""
SELECT 
df.Embarked,
AVG(df.Age) AS avg_age,
SUM(df.Age) AS tot_age,
MIN(df.AGE) AS min_age,
MAX(df.AGE) AS max_age,
COUNT(df.PassengerId) AS tot_passengers,
COUNT(DISTINCT df.Ticket) AS dist_tickets
FROM titanic AS df
GROUP BY df.embarked
""")

,Embarked,avg_age,tot_age,min_age,max_age,tot_passengers,dist_tickets
0,None,50.000000,100.00,38.00,62.0,2,1
1,C,30.814769,4005.92,0.42,71.0,168,122
2,Q,28.089286,786.50,2.00,70.5,77,66
3,S,29.445397,16312.75,0.67,80.0,644,494

AGGREGATING INFORMATION AT TWO LEVELS

AGGREGATING AT TWO LEVELS (COLUMNS)

In [24]:
ps.sqldf("""
SELECT
df.Sex,
df.Embarked,
AVG(df.Age) AS avg_age,
SUM(df.Age) AS sum_age,
MIN(df.Age) AS min_age,
MAX(df.Age) AS max_age,
COUNT(df.PassengerId) AS total_passengers,
COUNT(DISTINCT df.Ticket) as unique_tickets

FROM titanic as df
GROUP BY df.Embarked,df.Sex
""")

,Sex,Embarked,avg_age,sum_age,min_age,max_age,total_passengers,unique_tickets
0,female,None,50.000000,100.00,38.00,62.0,2,1
1,female,C,28.344262,1729.00,0.75,60.0,73,54
2,male,C,32.998841,2276.92,0.42,71.0,95,88
3,female,Q,24.291667,291.50,15.00,39.0,36,35
4,male,Q,30.937500,495.00,2.00,70.5,41,37
5,female,S,27.771505,5165.50,1.00,63.0,203,158
6,male,S,30.291440,11147.25,0.67,80.0,441,394

Aggregating information at "Embarked" and "Sex" levels 
#and also using "WHERE" to filter basis some conditions

In [25]:
ps.sqldf("""
SELECT 
df.Embarked,
df.Sex,
AVG(df.Age) as avg_tot,
SUM(df.Age) as sum_avg,
COUNT(df.PassengerId) as passenger_count,
COUNT(df.Ticket) as ticket_count
FROM titanic as df

WHERE age>=20 AND age <=50

GROUP BY df.Embarked ,df.Sex
""")

  Embarked     Sex    avg_tot  sum_avg  passenger_count  ticket_count
0     None  female  38.000000     38.0                1             1
1        C  female  33.705882   1146.0               34            34
2        C    male  31.528846   1639.5               52            52
3        Q  female  29.642857    207.5                7             7
4        Q    male  32.812500    262.5                8             8
5        S  female  31.964567   4059.5              127           127
6        S    male  31.632296   8129.5              257           257

In [26]:
ps.sqldf("""
SELECT df.Embarked,df.Age,
AVG(df.Age) AS avg_age,
MAX(df.Age) AS max_age,
COUNT(df.PassengerId) AS pas_count,
COUNT(DISTINCT df.Ticket) AS dist_ticket

FROM titanic AS df

WHERE age>=18

GROUP BY df.Embarked,df.Sex

ORDER BY df.Embarked DESC,df.Sex DESC
""")

  Embarked   Age    avg_age  max_age  pas_count  dist_ticket
0        S  80.0  33.420561     80.0        321          305
1        S  63.0  32.321192     63.0        151          137
2        Q  70.5  39.500000     70.5         12           12
3        Q  39.0  27.166667     39.0          9            9
4        C  71.0  35.540323     71.0         62           59
5        C  60.0  35.295455     60.0         44           35
6     None  62.0  50.000000     62.0          2            1

HAVING

Lastly, once you have aggregated the information, you can further put filters on the aggregated output using "HAVING". Always remember the difference between "WHERE" and "HAVING" as it is one of the most commonly asked interview questions. "WHERE" is used to filter the data directly from the tables while "HAVING" is used to filter the aggregated data you get as the output of a SQL

In [27]:
#Aggregating information at "Embarked" and "Sex" levels 
#and also using "WHERE" to filter basis some conditions
#and also using "HAVING" for fitering the output for buckets where average age is more than 30
#and also using "ORDER BY" for sorting the output in descending order
ps.sqldf("""

SELECT 
    df.Embarked,
    df.Sex,
    AVG(df.Age) AS avg_age,
    SUM(df.Age) AS tot_age,
    MIN(df.Age) AS min_age,
    MAX(df.Age) AS max_age,
    COUNT(df.PassengerId) AS tot_passengers,
    COUNT(DISTINCT df.Ticket) AS dist_tickets
    
FROM titanic AS df

WHERE age >= 18
    AND age <=60
    
GROUP BY df.Embarked,
    df.Sex

HAVING avg_age > 30

ORDER BY df.Embarked DESC,
    df.Sex DESC

""")

,Embarked,Sex,avg_age,tot_age,min_age,max_age,tot_passengers,dist_tickets
0,S,male,31.941368,9806.0,18.0,60.0,307,292
1,S,female,31.909396,4754.5,18.0,58.0,149,136
2,Q,male,33.850000,338.5,19.0,57.0,10,10
3,C,male,33.838983,1996.5,18.0,60.0,59,56
4,C,female,35.295455,1553.0,18.0,60.0,44,35
5,None,female,38.000000,38.0,38.0,38.0,1,1

<b>Remember the order - First we used "WHERE", then "GROUP BY", then "HAVING" and lastly "ORDER BY"</b>

# JOINS

JOINS are one of the most important and most frequently asked concept in SQL ,
so let us see JOINS

CREATING A NEW TABLE

In [28]:
cities = pd.DataFrame({'code':['S','C','L'],'city':['Southampton','Cherbrough','London']})
cities

  code         city
0    S  Southampton
1    C   Cherbrough
2    L       London

Let's see different unique codes in original dataset

In [29]:
ps.sqldf("""
SELECT DISTINCT df.Embarked
FROM titanic as df""")

  Embarked
0        S
1        C
2        Q
3     None

So we can see only S and C are common in both tables

INNER JOIN


INNER JOIN gives rows corresponding to only the common values(in the columns used in the inner join condition) between the two tables

In [30]:
ps.sqldf("""

SELECT 
    c.city,
    df.Embarked,
    df.Sex,
    AVG(df.Age) AS avg_age,
    SUM(df.Age) AS tot_age,
    MIN(df.Age) AS min_age,
    MAX(df.Age) AS max_age,
    COUNT(df.PassengerId) AS tot_passengers,
    COUNT(DISTINCT df.Ticket) AS dist_tickets
    
FROM titanic AS df

INNER JOIN cities AS c
    ON df.Embarked = c.code

GROUP BY df.Embarked,
    df.Sex

""")

,city,Embarked,Sex,avg_age,tot_age,min_age,max_age,tot_passengers,dist_tickets
0,Cherbrough,C,female,28.344262,1729.00,0.75,60.0,73,54
1,Cherbrough,C,male,32.998841,2276.92,0.42,71.0,95,88
2,Southampton,S,female,27.771505,5165.50,1.00,63.0,203,158
3,Southampton,S,male,30.291440,11147.25,0.67,80.0,441,394

In [31]:
ps.sqldf("""

SELECT 
    c.city,
    df.Embarked,
    df.Sex,
    AVG(df.Age) AS avg_age,
    SUM(df.Age) AS tot_age,
    MIN(df.Age) AS min_age,
    MAX(df.Age) AS max_age,
    COUNT(df.PassengerId) AS tot_passengers,
    COUNT(DISTINCT df.Ticket) AS dist_tickets
    
FROM titanic AS df

LEFT JOIN cities AS c
    ON df.Embarked = c.code

GROUP BY df.Embarked,
    df.Sex

""")

,city,Embarked,Sex,avg_age,tot_age,min_age,max_age,tot_passengers,dist_tickets
0,None,None,female,50.000000,100.00,38.00,62.0,2,1
1,Cherbrough,C,female,28.344262,1729.00,0.75,60.0,73,54
2,Cherbrough,C,male,32.998841,2276.92,0.42,71.0,95,88
3,None,Q,female,24.291667,291.50,15.00,39.0,36,35
4,None,Q,male,30.937500,495.00,2.00,70.5,41,37
5,Southampton,S,female,27.771505,5165.50,1.00,63.0,203,158
6,Southampton,S,male,30.291440,11147.25,0.67,80.0,441,394